//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class ApplyTransitionHistory :Entity
    {
        public ApplyTransitionHistory()
        {
          this.AllowedToUserNames= string.Empty;
          this.InitialState= string.Empty;
          this.DestinationState= string.Empty;
          this.Command= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public System.Guid ApplyId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.Guid? UserId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string AllowedToUserNames { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? TransitionTime { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public long Order { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string InitialState { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string DestinationState { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Command { get; set; }

    }
}