//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 分类类型
	/// </summary>
    public partial class CategoryType : Entity
    {
        public CategoryType()
        {
          this.Name= string.Empty;
          this.Code= string.Empty;
          this.CreateTime= DateTime.Now;
          this.CreateUser= string.Empty;
        }

        /// <summary>
	    /// 名称
	    /// </summary>
        public string Name { get; set; }
        /// <summary>
	    /// 编码
	    /// </summary>
        public string Code { get; set; }
        /// <summary>
	    /// 创建日期
	    /// </summary>
        public System.DateTime? CreateTime { get; set; }
        /// <summary>
	    /// 创建人
	    /// </summary>
        public string CreateUser { get; set; }

    }
}