//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 多对多关系集中映射
	/// </summary>
    public partial class Relevance :Entity
    {
        public Relevance()
        {
            this.Description= string.Empty;
          this.Key= string.Empty;
          this.Status= 0;
          this.OperateTime= DateTime.Now;
          this.OperatorId= 0;
        }

        /// <summary>
	    /// 描述
	    /// </summary>
        public string Description { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Key { get; set; }
        /// <summary>
	    /// 状态
	    /// </summary>
        public int Status { get; set; }
        /// <summary>
	    /// 授权时间
	    /// </summary>
        public System.DateTime OperateTime { get; set; }
        /// <summary>
	    /// 授权人
	    /// </summary>
        public int OperatorId { get; set; }
        /// <summary>
	    /// 第一个表主键ID
	    /// </summary>
        public System.Guid FirstId { get; set; }
        /// <summary>
	    /// 第二个表主键ID
	    /// </summary>
        public System.Guid SecondId { get; set; }

    }
}