//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 用户基本信息表
	/// </summary>
    public partial class User : Entity
    {
        public User()
        {
          this.Account= string.Empty;
          this.Password= string.Empty;
          this.Name= string.Empty;
          this.Sex= 0;
          this.Status= 0;
          this.Type= 0;
          this.BizCode= string.Empty;
          this.CreateTime= DateTime.Now;
          this.CrateId= string.Empty;
        }

        /// <summary>
	    /// 用户登录帐号
	    /// </summary>
        public string Account { get; set; }
        /// <summary>
	    /// 密码
	    /// </summary>
        public string Password { get; set; }
        /// <summary>
	    /// 用户姓名
	    /// </summary>
        public string Name { get; set; }
        /// <summary>
	    /// 性别
	    /// </summary>
        public int Sex { get; set; }
        /// <summary>
	    /// 用户状态
	    /// </summary>
        public int Status { get; set; }
        /// <summary>
	    /// 用户类型
	    /// </summary>
        public int Type { get; set; }
        /// <summary>
	    /// 业务对照码
	    /// </summary>
        public string BizCode { get; set; }
        /// <summary>
	    /// 经办时间
	    /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
	    /// 创建人
	    /// </summary>
        public string CrateId { get; set; }

    }
}