//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class User :Entity
    {
        public User()
        {
            this.Account= string.Empty;
          this.Password= string.Empty;
          this.Name= string.Empty;
          this.Sex= 0;
          this.Status= 0;
          this.Type= 0;
          this.BizCode= string.Empty;
          this.CreateTime= DateTime.Now;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string Account { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Password { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Name { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int Sex { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int Status { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int Type { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string BizCode { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime CreateTime { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.Guid? CrateId { get; set; }
    }
}