//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class WFFrmMain :Entity
    {
        public WFFrmMain()
        {
          this.FrmCode= string.Empty;
          this.FrmName= string.Empty;
          this.FrmType= string.Empty;
          this.FrmDbId= string.Empty;
          this.FrmTable= string.Empty;
          this.FrmTableId= string.Empty;
          this.FrmContent= string.Empty;
          this.Description= string.Empty;
          this.CreateDate= DateTime.Now;
          this.CreateUserId= string.Empty;
          this.CreateUserName= string.Empty;
          this.ModifyDate= DateTime.Now;
          this.ModifyUserId= string.Empty;
          this.ModifyUserName= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string FrmCode { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FrmName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FrmType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FrmDbId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FrmTable { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? IsSystemTable { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FrmTableId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FrmContent { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? SortCode { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? DeleteMark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? EnabledMark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Description { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CreateUserId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CreateUserName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifyDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifyUserId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifyUserName { get; set; }

    }
}