//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class WFProcessTransitionHistory :Entity
    {
        public WFProcessTransitionHistory()
        {
          this.ProcessId= Guid.Empty;
          this.FromNodeId= string.Empty;
          this.FromNodeName= string.Empty;
          this.ToNodeId= string.Empty;
          this.ToNodeName= string.Empty;
          this.TransitionSate= 0;
          this.IsFinish= 0;
          this.CreateDate= DateTime.Now;
          this.CreateUserId= string.Empty;
          this.CreateUserName= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public Guid ProcessId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FromNodeId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? FromNodeType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string FromNodeName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ToNodeId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? ToNodeType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ToNodeName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int TransitionSate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int IsFinish { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CreateUserId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CreateUserName { get; set; }

    }
}