//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class WFProcessScheme :Entity
    {
        public WFProcessScheme()
        {
          this.SchemeContent= string.Empty;
          this.SchemeInfoId= Guid.Empty;
          this.SchemeVersion= string.Empty;
          this.ProcessType= 0;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string SchemeContent { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public Guid SchemeInfoId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SchemeVersion { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int ProcessType { get; set; }


        #region 扩展操作
        /// <summary>
        /// 新增调用
        /// </summary>
        public  void Create()
        {
            this.Id = Guid.NewGuid();
        }
        /// <summary>
        /// 编辑调用
        /// </summary>
        /// <param name="keyValue"></param>
        public void Modify(Guid keyValue)
        {
            this.Id = keyValue;
        }
        #endregion
    }
}