//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class WFSchemeInfo :Entity
    {
        public WFSchemeInfo()
        {
          this.SchemeCode= string.Empty;
          this.SchemeName= string.Empty;
          this.SchemeType= string.Empty;
          this.SchemeVersion= string.Empty;
          this.SchemeCanUser= string.Empty;
          this.DeleteMark= 0;
          this.EnabledMark= 0;
          this.Description= string.Empty;
          this.CreateDate= DateTime.Now;
          this.CreateUserId= string.Empty;
          this.CreateUserName= string.Empty;
          this.ModifyDate= DateTime.Now;
          this.ModifyUserId= string.Empty;
          this.ModifyUserName= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string SchemeCode { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SchemeName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SchemeType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SchemeVersion { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string SchemeCanUser { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? FrmType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? AuthorizeType { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int? SortCode { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int DeleteMark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int EnabledMark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Description { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime CreateDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CreateUserId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string CreateUserName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.DateTime? ModifyDate { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifyUserId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ModifyUserName { get; set; }

    }
}