//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class WorkflowScheme 
    {
        public WorkflowScheme()
        {
          this.Code= string.Empty;
          this.Scheme= string.Empty;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public string Code { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Scheme { get; set; }

    }
}