//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 分类表
	/// </summary>
    public partial class Category : Entity
    {
        public Category()
        {
          this.CascadeId= string.Empty;
          this.Name= string.Empty;
          this.Code= string.Empty;
          this.Status= 0;
          this.SortNo= 0;
          this.TypeId= string.Empty;
          this.ParentId= string.Empty;
        }

        /// <summary>
	    /// 节点语义ID
	    /// </summary>
        public string CascadeId { get; set; }
        /// <summary>
	    /// 名称
	    /// </summary>
        public string Name { get; set; }
        /// <summary>
	    /// 编号
	    /// </summary>
        public string Code { get; set; }
        /// <summary>
	    /// 当前状态
	    /// </summary>
        public int Status { get; set; }
        /// <summary>
	    /// 排序号
	    /// </summary>
        public int SortNo { get; set; }
        /// <summary>
	    /// 分类所属科目
	    /// </summary>
        public string TypeId { get; set; }
        /// <summary>
	    /// 父节点流水号
	    /// </summary>
        public string ParentId { get; set; }

    }
}