//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
    ///
    /// </summary>
    [Table("FlowApprover")]
    public class FlowApprover : TreeEntity
    {
        public FlowApprover()
        {
            this.Reason = "";
            this.ApproverName = "";
            this.InstanceId = "";
            this.VerifyComment = "";
            this.CascadeId = "";
            this.ApproverId = "";
            this.ApproveType = 0;
            this.CreateDate = DateTime.Now;
            this.CreateUserName = "";
            this.ParentId = "";
            this.VerifyDate = DateTime.Now;
            this.Status = 0;
            this.ActivityId = "";
            this.OrderNo = 0;
            this.CreateUserId = "";
        }

        /// <summary>
        ///加签原因
        /// </summary>
        [Description("加签原因")]
        public string Reason { get; set; }

        /// <summary>
        ///审批人
        /// </summary>
        [Description("审批人")]
        public string ApproverName { get; set; }

        /// <summary>
        ///工作流实例Id
        /// </summary>
        [Description("工作流实例Id")]
        public string InstanceId { get; set; }

        /// <summary>
        ///审批意见
        /// </summary>
        [Description("审批意见")]
        public string VerifyComment { get; set; }
        

        /// <summary>
        ///审批人ID
        /// </summary>
        [Description("审批人ID")]
        public string ApproverId { get; set; }

        /// <summary>
        ///类型（0顺序，1并行且，2并行或）
        /// </summary>
        [Description("类型（0顺序，1并行且，2并行或）")]
        public int ApproveType { get; set; }

        /// <summary>
        ///加签时间
        /// </summary>
        [Description("加签时间")]
        public DateTime? CreateDate { get; set; }

        /// <summary>
        ///加签人
        /// </summary>
        [Description("加签人")]
        public string CreateUserName { get; set; }

        /// <summary>
        ///审批日期
        /// </summary>
        [Description("审批日期")]
        public DateTime? VerifyDate { get; set; }

        /// <summary>
        ///状态（0未处理，1通过，2未通过，3驳回）
        /// </summary>
        [Description("状态（0未处理，1通过，2未通过，3驳回）")]
        public int Status { get; set; }

        /// <summary>
        ///当前节点ID
        /// </summary>
        [Description("当前节点ID")]
        public string ActivityId { get; set; }

        /// <summary>
        ///顺序号（当类型为0时）
        /// </summary>
        [Description("顺序号（当类型为0时）")]
        public int? OrderNo { get; set; }

        /// <summary>
        ///加签人Id
        /// </summary>
        [Description("加签人Id")]
        public string CreateUserId { get; set; }
        
        /// <summary>
        ///是否回到加签节点
        /// <para>如果不需要，则加签完成后自动审批完成，否则还需要当前节点审批</para>
        /// </summary>
        [Description("是否回到加签节点")]
        public bool? ReturnToSignNode { get; set; }
    }
}