//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 工作流实例模板对应表，防止创建实例后原模板被改
	/// </summary>
    public partial class FlowInstanceScheme : Entity
    {
        public FlowInstanceScheme()
        {
          this.SchemeContent= string.Empty;
          this.SchemeId= string.Empty;
          this.SchemeVersion= string.Empty;
          this.ProcessType= 0;
        }

        /// <summary>
	    /// 流程模板内容
	    /// </summary>
        public string SchemeContent { get; set; }
        /// <summary>
	    /// 流程模板ID
	    /// </summary>
        public string SchemeId { get; set; }
        /// <summary>
	    /// 流程内容版本
	    /// </summary>
        public string SchemeVersion { get; set; }
        /// <summary>
	    /// 类型(0正常,3草稿)
	    /// </summary>
        public int ProcessType { get; set; }

    }
}