//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 工作流实例模板对应表
	/// </summary>
    public partial class WFProcessScheme : Entity
    {
        public WFProcessScheme()
        {
          this.SchemeContent= string.Empty;
          this.SchemeInfoId= string.Empty;
          this.SchemeVersion= string.Empty;
        }

        /// <summary>
	    /// 流程模板内容
	    /// </summary>
        public string SchemeContent { get; set; }
        /// <summary>
	    /// 流程模板ID
	    /// </summary>
        public string SchemeInfoId { get; set; }
        /// <summary>
	    /// 流程内容版本
	    /// </summary>
        public string SchemeVersion { get; set; }
        /// <summary>
	    /// 类型(0正常,3草稿)
	    /// </summary>
        public int? ProcessType { get; set; }

        #region 扩展操作
        /// <summary>
        /// 新增调用
        /// </summary>
        public void Create()
        {
            this.Id = Guid.NewGuid().ToString();
        }
        /// <summary>
        /// 编辑调用
        /// </summary>
        /// <param name="keyValue"></param>
        public void Modify(string keyValue)
        {
            this.Id = keyValue;
        }
        #endregion

    }
}