//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 入库通知单（入库订单）
	/// </summary>
    [Table("WmsInboundOrderTbl")]
    public partial class WmsInboundOrderTbl : Entity
    {
        public WmsInboundOrderTbl()
        {
          this.ExternalNo= string.Empty;
          this.ExternalType= string.Empty;
          this.Status= 0;
          this.OrderType= string.Empty;
          this.GoodsType= string.Empty;
          this.PurchaseNo= string.Empty;
          this.StockId= string.Empty;
          this.OwnerId= string.Empty;
          this.ShipperId= string.Empty;
          this.SupplierId= string.Empty;
          this.ScheduledInboundTime= DateTime.Now;
          this.Remark= string.Empty;
          this.TransferType= string.Empty;
          this.ReturnBoxNum= 0;
          this.CreateTime= DateTime.Now;
          this.CreateUserId= string.Empty;
          this.CreateUserName= string.Empty;
          this.UpdateTime= DateTime.Now;
          this.UpdateUserId= string.Empty;
          this.UpdateUserName= string.Empty;
        }

        
        /// <summary>
        /// 相关单据号
        /// </summary>
        [Description("相关单据")]
        public string ExternalNo { get; set; }
        /// <summary>
        /// 相关单据类型
        /// </summary>
        [Description("相关单据类型")]
        [Browsable(false)]
        public string ExternalType { get; set; }
        /// <summary>
        /// 状态
        /// </summary>
        [Description("状态")]
        public int Status { get; set; }
        /// <summary>
        /// 入库类型
        /// </summary>
        [Description("入库类型")]
        public string OrderType { get; set; }
        /// <summary>
        /// 商品类别
        /// </summary>
        [Description("商品类别")]
        public string GoodsType { get; set; }
        /// <summary>
        /// 采购单号
        /// </summary>
        [Description("采购单号")]
        public string PurchaseNo { get; set; }
        /// <summary>
        /// 仓库编号
        /// </summary>
        [Description("仓库编号")]
        [Browsable(false)]
        public string StockId { get; set; }
        /// <summary>
        /// 货主
        /// </summary>
        [Description("货主")]
        [Browsable(false)]
        public string OwnerId { get; set; }
        /// <summary>
        /// 承运人编号
        /// </summary>
        [Description("承运人")]
        [Browsable(false)]
        public string ShipperId { get; set; }
        /// <summary>
        /// 供应商编号
        /// </summary>
        [Description("供应商编号")]
        [Browsable(false)]
        public string SupplierId { get; set; }
        /// <summary>
        /// 预定入库时间
        /// </summary>
        [Description("预定时间")]
        public System.DateTime? ScheduledInboundTime { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        [Description("备注")]
        [Browsable(false)]
        public string Remark { get; set; }
        /// <summary>
        /// 有效标志
        /// </summary>
        [Description("有效标志")]
        public bool Enable { get; set; }
        /// <summary>
        /// 承运方式
        /// </summary>
        [Description("承运方式")]
        public string TransferType { get; set; }
        /// <summary>
        /// 是否入保税
        /// </summary>
        [Description("是否入保税库")]
        public bool InBondedArea { get; set; }
        /// <summary>
        /// 销退箱数
        /// </summary>
        [Description("销退箱数")]
        public decimal ReturnBoxNum { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        [Description("创建时间")]
        public System.DateTime CreateTime { get; set; }
        /// <summary>
        /// 创建人ID
        /// </summary>
        [Description("创建人ID")]
        [Browsable(false)]
        public string CreateUserId { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        [Description("创建人")]
        public string CreateUserName { get; set; }
        /// <summary>
        /// 最后更新时间
        /// </summary>
        [Description("最后更新")]
        public System.DateTime? UpdateTime { get; set; }
        /// <summary>
        /// 最后更新人ID
        /// </summary>
        [Description("最后更新人ID")]
        [Browsable(false)]
        public string UpdateUserId { get; set; }
        /// <summary>
        /// 最后更新人
        /// </summary>
        [Description("最后更新人")]
        public string UpdateUserName { get; set; }
        
        /// <summary>
        /// 所属部门
        /// </summary>
        [Description("所属部门")]
        public string OrgId { get; set; }
    }
}