//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.App.Request
{
    /// <summary>
       ///
       /// </summary>

    public class AddOrUpdateSysPrinterPlanReq
    {
        /// <summary>
       ///方案名称
       /// </summary>
       public string Name { get; set; }

       /// <summary>
       ///方案ID
       /// </summary>
       public string Id { get; set; }

       /// <summary>
       ///创建人
       /// </summary>
       public string CreateUser { get; set; }

       /// <summary>
       ///数据源;打印方案对应的数据来源SQL
       /// </summary>
       public string SourceSql { get; set; }

       /// <summary>
       ///中文视图名;设计打印方案时，提供中文快捷按钮的视图来源
       /// </summary>
       public string CloumnView { get; set; }

       /// <summary>
       ///打印方案内容;打印方案JSON对象
       /// </summary>
       public string PlanContent { get; set; }

       /// <summary>
       ///创建日期
       /// </summary>
       public DateTime CreateTime { get; set; }

       /// <summary>
       ///是否可用
       /// </summary>
       public bool Disable { get; set; }

       
    }
}