//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using OpenAuth.Domain;
using OpenAuth.Repository.Models;
using OpenAuth.Repository.Models.Mapping;
using OpenAuth.Repository.Workflow.Mapping;

namespace OpenAuth.Repository.Workflow
{
    public partial class WorkflowContext: DbContext
    {
        static WorkflowContext()
        {
            Database.SetInitializer< OpenAuthDBContext>(null);
        }
        public WorkflowContext()
            :base("Name=WorkFlow")
        { }

        public WorkflowContext(string nameOrConnectionString)
            : base(nameOrConnectionString)
        { }


        public System.Data.Entity.DbSet<WorkflowScheme> WorkflowSchemes { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new WorkflowSchemeMap());

        }
    }
}