//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
//------------------------------------------------------------------------------

namespace OpenAuth.App.Request
{
    /// <summary>
    /// 加签人具体信息
    /// </summary>
    public class AddApproverDtlReq
    {
        /// <summary>
        ///Id
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        ///加签人姓名
        /// </summary>
        public string ApproverName { get; set; }

        /// <summary>
        ///加签人ID
        /// </summary>
        public string ApproverId { get; set; }


        /// <summary>
        ///顺序号（当类型为0时）
        /// </summary>
        public int? OrderNo { get; set; }
    }
}