//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace OpenAuth.App.Request
{
    /// <summary>
    /// 创建或修改加签信息
    /// </summary>
    public class AddApproverReq
    {
        /// <summary>
        ///加签原因
        /// </summary>
        public string Reason { get; set; }


        /// <summary>
        ///工作流实例Id
        /// </summary>
        public string InstanceId { get; set; }


        /// <summary>
        ///类型（0顺序，1并行且，2并行或）
        /// </summary>
        public int ApproveType { get; set; }

        /// <summary>
        ///父节点ID，应对多次加签
        /// </summary>
        public string ParentId { get; set; }

        /// <summary>
        ///当前节点ID
        /// </summary>
        public string ActivityId { get; set; }
        
        /// <summary>
        ///是否回到加签节点
        /// <para>如果不需要，则加签完成后自动审批完成，否则还需要当前节点审批</para>
        /// </summary>
        public bool? ReturnToSignNode { get; set; }

        public List<AddApproverDtlReq> Approvers { get; set; }
    }
}