//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
//------------------------------------------------------------------------------

namespace OpenAuth.App.Request
{
    /// <summary>
    /// 创建或修改加签信息
    /// </summary>
    public class AddApproverReq
    {
        /// <summary>
        ///Id
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        ///加签原因
        /// </summary>
        public string Reason { get; set; }

        /// <summary>
        ///审批人
        /// </summary>
        public string ApproverName { get; set; }

        /// <summary>
        ///工作流实例Id
        /// </summary>
        public string InstanceId { get; set; }

        /// <summary>
        ///审批人ID
        /// </summary>
        public string ApproverId { get; set; }

        /// <summary>
        ///类型（0顺序，1并行且，2并行或）
        /// </summary>
        public int ApproveType { get; set; }

        /// <summary>
        ///父节点ID，应对多次加签
        /// </summary>
        public string ParentId { get; set; }

        /// <summary>
        ///当前节点ID
        /// </summary>
        public string ActivityId { get; set; }

        /// <summary>
        ///顺序号（当类型为0时）
        /// </summary>
        public int? OrderNo { get; set; }
    }
}