//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.App.Request
{
    /// <summary>
       ///
       /// </summary>

    public class AddOrUpdateFlowApproverReq
    {
        /// <summary>
       ///Id
       /// </summary>
       public string Id { get; set; }

       /// <summary>
       ///加签原因
       /// </summary>
       public string Reason { get; set; }

       /// <summary>
       ///审批人
       /// </summary>
       public string ApproverName { get; set; }

       /// <summary>
       ///工作流实例Id
       /// </summary>
       public string InstanceId { get; set; }

       /// <summary>
       ///审批意见
       /// </summary>
       public string VerifyComment { get; set; }

       /// <summary>
       ///审批人ID
       /// </summary>
       public string ApproverId { get; set; }

       /// <summary>
       ///类型（0顺序，1并行且，2并行或）
       /// </summary>
       public int ApproveType { get; set; }
        
       /// <summary>
       ///父节点ID，应对多次加签
       /// </summary>
       public string ParentId { get; set; }

       /// <summary>
       ///审批日期
       /// </summary>
       public DateTime? VerifyDate { get; set; }

       /// <summary>
       ///状态（0未处理，1通过，2未通过，3驳回）
       /// </summary>
       public int Status { get; set; }

       /// <summary>
       ///当前节点ID
       /// </summary>
       public string ActivityId { get; set; }

       /// <summary>
       ///顺序号（当类型为0时）
       /// </summary>
       public int? OrderNo { get; set; }
       
    }
}