//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
//------------------------------------------------------------------------------

using System;

namespace OpenAuth.App.Request
{
    /// <summary>
    /// 审批加签节点
    /// </summary>
    public class VerifyApproverReq
    {
        /// <summary>
        ///Id
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        ///审批意见
        /// </summary>
        public string VerifyComment { get; set; }

        /// <summary>
        ///审批日期
        /// </summary>
        public DateTime? VerifyDate { get; set; }

        /// <summary>
        ///状态（0未处理，1通过，2未通过，3驳回）
        /// </summary>
        public int Status { get; set; }
    }
}