//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

namespace OpenAuth.App.Request
{
    /// <summary>
	/// 分类表，也可用作数据字典。表示一个全集，比如：男、女、未知。关联的分类类型表示按什么进行的分类，如：按照性别对人类对象集
	/// </summary>
    public  class AddOrUpdateCategoryReq
    {

        public string Id { get; set; }

        /// <summary>
        /// 分类名称或描述
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 分类标识
        /// </summary>
        public string DtCode { get; set; }
        /// <summary>
        /// 通常与分类标识一致，但万一有不一样的情况呢？
        /// </summary>
        public string DtValue { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public bool Enable { get; set; }
        /// <summary>
        /// 排序号
        /// </summary>
        public int SortNo { get; set; }
        /// <summary>
        /// 详细说明，基本没啥用
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// 分类的ID
        /// </summary>
        public string TypeId { get; set; }
        
    }
}