//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using OpenAuth.Domain;

namespace OpenAuth.Repository.Workflow.Mapping
{
    public partial class WorkflowSchemeMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WorkflowScheme>
    {
        public WorkflowSchemeMap()
        {
            // table
            ToTable("WorkflowScheme", "dbo");

            // keys
            HasKey(t => t.Code);

            // Properties
            Property(t => t.Code)
                .HasColumnName("Code")
                .HasMaxLength(256)
                .IsRequired();
            Property(t => t.Scheme)
                .HasColumnName("Scheme")
                .IsRequired();

            // Relationships
        }
    }
}
