//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 同意申请单
	/// </summary>
    public partial class CommonApply : Entity
    {
        public CommonApply()
        {
         this.Sort= 0;
          this.Name= string.Empty;
          this.Comment= string.Empty;
          this.State= string.Empty;
          this.StateName= string.Empty;
          this.ApplyTime = DateTime.Now;
        }

        /// <summary>
	    /// 
	    /// </summary>
        public int Sort { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public DateTime ApplyTime { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Name { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Comment { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string State { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string StateName { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.Guid UserId { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public System.Guid? ControllerUserId { get; set; }


        public string WorkflowName { get; set; }
    }
}