//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 键值参数
	/// </summary>
    public partial class Param
    {
        public Param()
        {
          this.Id= 0;
          this.Value= string.Empty;
          this.Key= string.Empty;
          this.CategoryId= 0;
          this.SortNo= 0;
          this.Status= 0;
          this.Description= string.Empty;
        }

        /// <summary>
	    /// ID
	    /// </summary>
        public int Id { get; set; }
        /// <summary>
	    /// 值
	    /// </summary>
        public string Value { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Key { get; set; }
        /// <summary>
	    /// 所属分类
	    /// </summary>
        public int CategoryId { get; set; }
        /// <summary>
	    /// 排序号
	    /// </summary>
        public int SortNo { get; set; }
        /// <summary>
	    /// 状态
	    /// </summary>
        public int Status { get; set; }
        /// <summary>
	    /// 描述
	    /// </summary>
        public string Description { get; set; }

    }
}