//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 出入库信息表
	/// </summary>
    public partial class Stock :Entity
    {
        public Stock()
        {
            this.Name= string.Empty;
          this.Number= 0;
          this.Price= 0;
          this.Status= 0;
          this.Viewable = string.Empty;
          this.Time= DateTime.Now;
        } 

        /// <summary>
	    /// 产品名称
	    /// </summary>
        public string Name { get; set; }
        /// <summary>
	    /// 产品数量
	    /// </summary>
        public int Number { get; set; }
        /// <summary>
	    /// 产品单价
	    /// </summary>
        public decimal Price { get; set; }
        /// <summary>
	    /// 出库/入库
	    /// </summary>
        public int Status { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Viewable { get; set; }
        /// <summary>
	    /// 操作时间
	    /// </summary>
        public System.DateTime Time { get; set; }
        /// <summary>
	    /// 组织ID
	    /// </summary>
        public System.Guid? OrgId { get; set; }

    }
}