//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 用户配置表
	/// </summary>
    public partial class UserCfg
    {
        public UserCfg()
        {
          this.Id= 0;
          this.Theme= string.Empty;
          this.Skin= string.Empty;
          this.NavBarStyle= string.Empty;
          this.TabFocusColor= string.Empty;
          this.NavTabIndex= 0;
        }

        /// <summary>
	    /// 用户ID
	    /// </summary>
        public int Id { get; set; }
        /// <summary>
	    /// 用户界面主题
	    /// </summary>
        public string Theme { get; set; }
        /// <summary>
	    /// 用户界面皮肤
	    /// </summary>
        public string Skin { get; set; }
        /// <summary>
	    /// 导航条按钮风格
	    /// </summary>
        public string NavBarStyle { get; set; }
        /// <summary>
	    /// Tab高亮颜色
	    /// </summary>
        public string TabFocusColor { get; set; }
        /// <summary>
	    /// 导航缺省活动页
	    /// </summary>
        public int NavTabIndex { get; set; }

    }
}