//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Domain
{
    /// <summary>
	/// 用户扩展信息表
	/// </summary>
    public partial class UserExt
    {
        public UserExt()
        {
          this.Id= 0;
          this.Email= string.Empty;
          this.Phone= string.Empty;
          this.Mobile= string.Empty;
          this.Address= string.Empty;
          this.Zip= string.Empty;
          this.Birthday= string.Empty;
          this.IdCard= string.Empty;
          this.Qq= string.Empty;
          this.DynamicField= string.Empty;
          this.ByteArrayId= 0;
          this.Remark= string.Empty;
          this.Field1= string.Empty;
          this.Field2= string.Empty;
          this.Field3= string.Empty;
        }

        /// <summary>
	    /// 用户ID
	    /// </summary>
        public int Id { get; set; }
        /// <summary>
	    /// 电子邮件
	    /// </summary>
        public string Email { get; set; }
        /// <summary>
	    /// 固定电话
	    /// </summary>
        public string Phone { get; set; }
        /// <summary>
	    /// 移动电话
	    /// </summary>
        public string Mobile { get; set; }
        /// <summary>
	    /// 联系地址
	    /// </summary>
        public string Address { get; set; }
        /// <summary>
	    /// 邮编
	    /// </summary>
        public string Zip { get; set; }
        /// <summary>
	    /// 生日
	    /// </summary>
        public string Birthday { get; set; }
        /// <summary>
	    /// 身份证号
	    /// </summary>
        public string IdCard { get; set; }
        /// <summary>
	    /// QQ
	    /// </summary>
        public string Qq { get; set; }
        /// <summary>
	    /// 动态扩展字段
	    /// </summary>
        public string DynamicField { get; set; }
        /// <summary>
	    /// 用户头像流文件ID
	    /// </summary>
        public int ByteArrayId { get; set; }
        /// <summary>
	    /// 备注
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 静态扩展字段1
	    /// </summary>
        public string Field1 { get; set; }
        /// <summary>
	    /// 静态扩展字段2
	    /// </summary>
        public string Field2 { get; set; }
        /// <summary>
	    /// 静态扩展字段3
	    /// </summary>
        public string Field3 { get; set; }

    }
}