//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

namespace OpenAuth.Domain
{
    /// <summary>
	/// 
	/// </summary>
    public partial class WorkflowInbox :Entity
    {
        /// <summary>
	    /// 工作流实体ID
	    /// </summary>
        public System.Guid ProcessId { get; set; }
        /// <summary>
	    ///  用户ID
	    /// </summary>
        public System.Guid IdentityId { get; set; }

    }
}