//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using OpenAuth.Domain;

namespace OpenAuth.Repository.Models.Mapping
{
    public partial class DicDetailMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DicDetail>
    {
        public DicDetailMap()
        {
            // table
            ToTable("DicDetail", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .IsRequired();
            Property(t => t.Value)
                .HasColumnName("Value")
                .HasMaxLength(100)
                .IsRequired();
            Property(t => t.Text)
                .HasColumnName("Text")
                .HasMaxLength(100)
                .IsRequired();
            Property(t => t.SortNo)
                .HasColumnName("SortNo")
                .IsRequired();
            Property(t => t.Status)
                .HasColumnName("Status")
                .IsRequired();
            Property(t => t.Description)
                .HasColumnName("Description")
                .HasMaxLength(100)
                .IsRequired();
            Property(t => t.DicId)
                .HasColumnName("DicId")
                .IsRequired();

            // Relationships
        }
    }
}
