//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using OpenAuth.Domain;

namespace OpenAuth.Repository.Models.Mapping
{
    public partial class DicIndexMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DicIndex>
    {
        public DicIndexMap()
        {
            // table
            ToTable("DicIndex", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .IsRequired();
            Property(t => t.Name)
                .HasColumnName("Name")
                .HasMaxLength(255)
                .IsRequired();
            Property(t => t.Key)
                .HasColumnName("Key")
                .HasMaxLength(100)
                .IsRequired();
            Property(t => t.SortNo)
                .HasColumnName("SortNo")
                .IsRequired();
            Property(t => t.Description)
                .HasColumnName("Description")
                .HasMaxLength(200)
                .IsRequired();
            Property(t => t.CategoryId)
                .HasColumnName("CategoryId")
                .IsOptional();

            // Relationships
        }
    }
}
