//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace OpenAuth.Repository.Models.Mapping
{
    public partial class WFFrmMainMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OpenAuth.Domain.WFFrmMain>
    {
        public WFFrmMainMap()
        {
            // table
            ToTable("WF_FrmMain", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .IsRequired();
            Property(t => t.FrmCode)
                .HasColumnName("FrmCode")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.FrmName)
                .HasColumnName("FrmName")
                .HasMaxLength(200)
                .IsOptional();
            Property(t => t.FrmType)
                .HasColumnName("FrmType")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.FrmDbId)
                .HasColumnName("FrmDbId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.FrmTable)
                .HasColumnName("FrmTable")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.IsSystemTable)
                .HasColumnName("isSystemTable")
                .IsOptional();
            Property(t => t.FrmTableId)
                .HasColumnName("FrmTableId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.FrmContent)
                .HasColumnName("FrmContent")
                .IsOptional();
            Property(t => t.SortCode)
                .HasColumnName("SortCode")
                .IsOptional();
            Property(t => t.DeleteMark)
                .HasColumnName("DeleteMark")
                .IsOptional();
            Property(t => t.EnabledMark)
                .HasColumnName("EnabledMark")
                .IsOptional();
            Property(t => t.Description)
                .HasColumnName("Description")
                .HasMaxLength(200)
                .IsOptional();
            Property(t => t.CreateDate)
                .HasColumnName("CreateDate")
                .IsOptional();
            Property(t => t.CreateUserId)
                .HasColumnName("CreateUserId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.CreateUserName)
                .HasColumnName("CreateUserName")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.ModifyDate)
                .HasColumnName("ModifyDate")
                .IsOptional();
            Property(t => t.ModifyUserId)
                .HasColumnName("ModifyUserId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.ModifyUserName)
                .HasColumnName("ModifyUserName")
                .HasMaxLength(50)
                .IsOptional();

            // Relationships
        }
    }
}
