//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace OpenAuth.Repository.Models.Mapping
{
    public partial class WFProcessOperationHistoryMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OpenAuth.Domain.WFProcessOperationHistory>
    {
        public WFProcessOperationHistoryMap()
        {
            // table
            ToTable("WF_ProcessOperationHistory", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .IsRequired();
            Property(t => t.ProcessId)
                .HasColumnName("ProcessId")
                .IsRequired();
            Property(t => t.Content)
                .HasColumnName("Content")
                .HasMaxLength(200)
                .IsRequired();
            Property(t => t.CreateDate)
                .HasColumnName("CreateDate")
                .IsRequired();
            Property(t => t.CreateUserId)
                .HasColumnName("CreateUserId")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.CreateUserName)
                .HasColumnName("CreateUserName")
                .HasMaxLength(50)
                .IsRequired();

            // Relationships
        }
    }
}
