//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using OpenAuth.Domain;

namespace OpenAuth.Repository.Models.Mapping
{
    public partial class WorkflowInboxMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WorkflowInbox>
    {
        public WorkflowInboxMap()
        {
            // table
            ToTable("WorkflowInbox", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .IsRequired();
            Property(t => t.ProcessId)
                .HasColumnName("ProcessId")
                .IsRequired();
            Property(t => t.IdentityId)
                .HasColumnName("IdentityId")
                .IsRequired();

            // Relationships
        }
    }
}
