//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace OpenAuth.Repository.Models.Mapping
{
    public partial class WFSchemeContentMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OpenAuth.Domain.WFSchemeContent>
    {
        public WFSchemeContentMap()
        {
            // table
            ToTable("WF_SchemeContent", "dbo");

            // keys
            HasKey(t => t.Id);

            // Properties
            Property(t => t.Id)
                .HasColumnName("Id")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.SchemeInfoId)
                .HasColumnName("SchemeInfoId")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.SchemeVersion)
                .HasColumnName("SchemeVersion")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.SchemeContent)
                .HasColumnName("SchemeContent")
                .IsOptional();
            Property(t => t.CreateDate)
                .HasColumnName("CreateDate")
                .IsOptional();
            Property(t => t.CreateUserId)
                .HasColumnName("CreateUserId")
                .HasMaxLength(50)
                .IsOptional();
            Property(t => t.CreateUserName)
                .HasColumnName("CreateUserName")
                .HasMaxLength(50)
                .IsOptional();

            // Relationships
        }
    }
}
