//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------

namespace OpenAuth.App.Request
{
    /// <summary>
	/// 同步表结构
	/// </summary>
    public class SyncStructureReq 
    {
        /// <summary>
        /// Id为空则为添加
        /// </summary>
        public string Id { get; set; }
        
        /// <summary>
        /// 表英文全称
        /// </summary>
        public string TableName { get; set; }
      
    }
}